version: '3.3'
services:
  db:
    image: mysql
    restart: always

    environment:
      MYSQL_DATABASE: 'imperio'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'imperiothisisaverysecretpassword'
      MYSQL_ROOT_PASSWORD: 'rootthisisaverysecretpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - imperio-db:/var/lib/mysql
volumes:
  imperio-db: