version: '3.3'
volumes:
    prometheus_data: {}
services:
  imperio:
    image: imperio-backend
    restart: always

    environment:
      - IMPERIO_SERVER_LISTEN_PORT=8000
      - IMPERIO_DATABASE_HOST=imperio-database.ck81rohysnal.us-east-2.rds.amazonaws.com
      - IMPERIO_DATABASE_NAME=imperio
      - IMPERIO_DATABASE_USER=admin
      - IMPERIO_DATABASE_PASSWORD=Imperio123!
      - IMPERIO_DATABASE_CONSOLE_OUTPUT=false
    ports:
      - '80:8000'
    expose:
      - '80'

  prometheus-server:
    image: prom/prometheus
    network_mode: host        
    ports:
      - 9090:9090
    expose:
      - 9090      
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana-ui:
    image: grafana/grafana
    network_mode: host            
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    user: "500"
    volumes:
      - ./gfdata:/var/lib/grafana
      #- ./monotoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml      

