// ============================================================
// Project            :  Imperio
// File               :  .\Imperio\game\gameScripts\client\clientNoticias.cs
// Copyright          :  
// Author             :  admin
// Created on         :  quarta-feira, 1 de julho de 2009 16:39
//
// Editor             :  Codeweaver v. 1.2.3430.42233
//
// Description        :  
//                    :  
//                    :  
// ============================================================

function initNoticiasSys()
{
	if(isObject($noticias_handler))
		return;
		
		
	$NoticiasSysNum++;

	$noticias_handler = newSimObj("noticias_handler", $NoticiasSysNum);
	$noticias_handler.initSimNoticias();
	$noticias_handler.sortearNovaNoticia();
}

function noticias_handler::initSimNoticias(%this)
{
	if(!isObject(%this.simNoticias))
	{
		%this.simNoticias = new SimSet();
		%this.criarTodasAsNoticias();
	}	
}

function noticias_handler::criarNoticia(%this, %titulo, %texto, %img, %just, %req, %reqQtdMin, %reqQtdMax, %especie, %prioridade)
{
	$noticiasObjNum++;
	%noticia = newSimObj("noticia_obj", $noticiasObjNum);	
	%noticia.num = $noticiasObjNum;
	%noticia.titulo = %titulo;
	%noticia.texto = %texto;
	%noticia.img = %img;
	%noticia.just = %just;
	%noticia.req = %req;
	%noticia.reqQtdMin = %reqQtdMin;
	%noticia.reqQtdMax = %reqQtdMax;
	%noticia.especie = %especie;
	%noticia.prioridade = %prioridade;
	
	%this.simNoticias.add(%noticia);
}

function noticias_handler::criarTodasAsNoticias(%this)
{
	//BÁSICO:
	%this.criarNoticia("LOGÍSTICA: APROVEITE SEUS MOVIMENTOS", "PROCURE SEMPRE <color:FDFDD8>USAR TODOS OS SEUS MOVIMENTOS <color:FFFFFF>A CADA RODADA.\nQUANTO MAIS ÁREAS VOCÊ POSSUIR, MAIS IMPERIAIS RECEBERÁ NAS PRÓXIMAS RODADAS.", "noticias_mapa.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("GRUPOS VALIOSOS: PENSANDO NO FUTURO", "NAS PRIMEIRAS RODADAS DE CADA PARTIDA TENTE CONQUISTAR <color:FDFDD8>GRUPOS QUE FORNEÇAM PETRÓLEO OU URÂNIO, ANTES DE QUAISQUER OUTROS. <color:FFFFFF>NA MAIORIA DAS VEZES ESTA SERÁ UMA BOA ESTRATÉGIA, POIS RENDERÁ RECURSOS MUITO RAPIDAMENTE.", "noticias_mapa.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("JOGADAS INICIAIS: SEJA EFICIENTE", "SEUS <color:FDFDD8>PRIMEIROS MOVIMENTOS <color:FFFFFF>DEFINIRÃO BOA PARTE DE CADA JOGO. PROCURE DESCOBRIR OS <color:FDFDD8>MELHORES LUGARES PARA POSICIONAR SUAS BASES DE ACORDO COM CADA GRUPO INICIAL. <color:FFFFFF>ISTO PODE FAZER A DIFERENÇA ENTRE A VITÓRIA E A DERROTA.", "noticias_mapa.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("DEFESA: MANTENHA SUAS BASES SEGURAS", "EVITE DEIXAR BASES DESPROTEGIDAS, OU PROTEGIDAS POR APENAS UM SOLDADO.\nPROTEGENDO SUAS BASES VOCÊ <color:FDFDD8>INTIMIDA OS ADVERSÁRIOS, <color:FFFFFF>MINIMIZANDO A CHANCE DE SER ATACADO.", "noticias_defesa.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("ACADEMIA IMPERIAL: DESENVOLVA HABILIDADES", "APÓS SUA PRIMEIRA VITÓRIA VOCÊ ABRE A ACADEMIA IMPERIAL E PODE DESENVOLVER PESQUISAS TECNOLÓGICAS. AS NOVAS TECNOLOGIAS LHE DARÃO <color:FDFDD8>VANTAGENS SOBRE OS ADVERSÁRIOS, <color:FFFFFF>AUMENTANDO SUAS CHANCES DE VITÓRIA.", "noticias_academia.png", "CENTER", "vitorias", 0, 1, "humano");	
	%this.criarNoticia("VENDENDO RECURSOS: COMO FICAR RICO", "VENDA AO BANCO <color:FDFDD8>MINÉRIO, PETRÓLEO E URÂNIO <color:FFFFFF>PARA FINANCIAR SEUS EXÉRCITOS.\nLEMBRE-SE DE QUE OS <color:FDFDD8>RECURSOS SÃO USADOS NA MAIORIA DOS OBJETIVOS <color:FFFFFF>E TAMBÉM <color:FDFDD8>VALEM PONTOS <color:FFFFFF>AO FINAL DA PARTIDA. PROCURE VENDER APENAS O NECESSÁRIO.", "noticias_recursos.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("INVESTINDO EM TECNOLOGIAS DA ACADEMIA", "QUANDO VOCÊ POSSUI UMA PESQUISA EM ANDAMENTO, O BOTÃO DE <color:FDFDD8>INVESTIR RECURSOS <color:FFFFFF>FICA ATIVO DURANTE AS PARTIDAS. PARA FINALIZAR UMA PESQUISA VOCÊ DEVE <color:FDFDD8>INVESTIR NELA OS RECURSOS GANHOS A CADA RODADA.", "noticias_recursos.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("BARRAS DE PROGRESSO E PESQUISAS", "AS BARRAS DE PROGRESSO EM PONTOS, VISIONÁRIO E ARREBATADOR INDICAM QUANTO FALTA PARA ABRIR NOVAS POSSIBILIDADES DE PESQUISA. <color:FDFDD8>SEMPRE QUE UMA BARRA É COMPLETADA, UMA NOVA PESQUISA FICA DISPONÍVEL NA ACADEMIA IMPERIAL.", "noticias_barrasDeProgresso.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("PATENTES: A BARRA DE VITÓRIAS", "NA ESPÉCIE HUMANA, AS 14 PATENTES SÃO AS SEGUINTES: RECRUTA, CADETE, ASPIRANTE, SARGENTO, TENENTE, CAPITÃO, MAJOR, CORONEL, GENERAL, MARECHAL, IMPERADOR, IMORTAL, LENDÁRIO E TITÃ. <color:FDFDD8>CADA PATENTE LHE DÁ MAIS IMPERIAIS NO INÍCIO DAS PARTIDAS.", "noticias_barrasDeProgresso.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("MORATÓRIAS: RECLAMANDO O QUE É SEU", "DECRETAR MORATÓRIA SIGNIFICA <color:FDFDD8>PARAR DE PAGAR A PARTE DO SEU ADVERSÁRIO <color:FFFFFF>EM UM ACORDO DE EXPLORAÇÃO. EM VEZ DE GANHAR O RECURSO DE DUAS EM DUAS RODADAS, VOCÊ GANHARÁ TODA RODADA E SEU ADVERSÁRIO DEIXARÁ DE RECEBER.", "noticias_recursos.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("ATAQUE E DEFESA DAS UNIDADES", "AS UNIDADES COMEÇAM FRACAS E PODEM SER MELHORADAS NA ACADEMIA. O RESULTADO DE UM COMBATE É <color:FDFDD8>INFLUENCIADO PELAS PESQUISAS DESENVOLVIDAS <color:FFFFFF>E VOCÊ PODE ESCOLHER INVESTIR MAIS EM DEFESA OU EM ATAQUE, <color:FDFDD8>CONFORME SEU JEITO DE JOGAR.", "noticias_atkDef.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("NEGOCIANDO COM OS ADVERSÁRIOS", "FAZER ACORDOS PODE MUDAR O RUMO DE UMA PARTIDA: SE VOCÊ PRECISA DE UM LOCAL ADVERSÁRIO, TENTE <color:FDFDD8>COMPRÁ-LO OU TROCAR POR ALGO QUE VOCÊ POSSUI. <color:FFFFFF>SE VOCÊ ENFRENTA UM ADVERSÁRIO MUITO FORTE, <color:FDFDD8>UNA-SE COM OUTROS PARA NEUTRALIZÁ-LO.", "noticias_diplomacia.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("COMBATES: UM É POUCO, DOIS É BOM", "AS <color:FDFDD8>DUAS UNIDADES MAIS FORTES <color:FFFFFF>DE CADA ÁREA PARTICIPAM DOS COMBATES. PROCURE SEMPRE TER <color:FDFDD8>PELO MENOS DUAS UNIDADES <color:FFFFFF>NAS SUAS ÁREAS ANTES DE ATACAR UM ADVERSÁRIO, E PREFIRA ATACÁ-LO ONDE ELE POSSUIR <color:FFFFFF>APENAS UMA.", "noticias_atkDef.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("FAZENDO ACORDOS: NEGOCIE COM TODOS", "FIQUE DE OLHO BOTÃO DE <color:FDFDD8>ACORDOS POSSÍVEIS. <color:FFFFFF>SEMPRE QUE ELE ESTIVER ACESO VOCÊ PODERÁ <color:FDFDD8>INICIAR ACORDOS <color:FFFFFF>COM OUTROS JOGADORES. QUANTO MAIS ACORDOS VOCÊ FIZER, MAIS VANTAGENS TERÁ SOBRE CADA ADVERSÁRIO.", "noticias_diplomacia.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("ACORDOS DE TROCA: GANHE PONTOS", "QUANDO VOCÊ RECEBE UMA MISSÃO DE CONSTRUÇÃO EM UMA ÁREA ADVERSÁRIA <color:FDFDD8>É POSSÍVEL TROCÁ-LA, <color:FFFFFF>DESDE QUE O ADVERSÁRIO POSSUA UMA MISSÃO IGUAL EM UMA ÁREA QUE PERTENCE A VOCÊ. <color:FDFDD8>USE O BOTÃO DE ACORDOS POSSÍVEIS PARA FAZER TROCAS.", "noticias_diplomacia.png", "CENTER", "vitorias", 0, 25, "humano");	
		
	//DICAS:
	%this.criarNoticia("VISITANDO ÁREAS ADVERSÁRIAS", "SEGURANDO A <color:FDFDD8>TECLA SHIFT <color:FFFFFF>E TENTANDO MOVER UMA PEÇA PARA UMA ÁREA ADVERSÁRIA VOCÊ ENVIARÁ UM <color:FDFDD8>PEDIDO DE PASSAGEM AMIGÁVEL. <color:FFFFFF>ASSIM, É POSSÍVEL TRANSITAR PELO MUNDO <color:FDFDD8>SEM ENTRAR EM GUERRAS DESNECESSÁRIAS.", "noticias_diplomacia.png", "CENTER", "vitorias", 0, 50, "humano");	
	%this.criarNoticia("PING: AVISANDO PARCEIROS EM POTENCIAL", "CLIQUE NO <color:FDFDD8>BOTÃO CIRCULAR <color:FFFFFF>AO LADO DO NOME DE UM ADVERSÁRIO E <color:FDFDD8>CLIQUE EM UMA ÁERA DO TABULEIRO <color:FFFFFF>PARA ENVIAR UM PING, CHAMANDO ATENÇÃO DESTE JOGADOR PARA A ÁREA CLICADA. UTILIZE PINGS PARA <color:FDFDD8>FALICILITAR A COMUNICAÇÃO.", "noticias_ping.png", "CENTER", "vitorias", 0, 50, "humano");	
	%this.criarNoticia("CTRL + Z: DESFAZER MOVIMENTO", "É POSSÍVEL DESFAZER UM MOVIMENTO EQUIVOCADO PRESSIONANDO AS TECLAS <color:FDFDD8>CTRL+Z <color:FFFFFF>NO TECLADO. SOMENTE O ÚLTIMO MOVIMENTO PODE SER DESFEITO, E NUNCA LOGO APÓS TER CONSTRÚIDO BASES OU PRODUZIDO UNIDADES.", "noticias_undo.png", "CENTER", "vitorias", 0, 50, "humano");	
	%this.criarNoticia("ZOOM: APROXIMANDO O TABULEIRO", "VOCÊ PODE APROXIMAR O TABULEIRO USANDO A <color:FDFDD8>RODINHA DO MOUSE <color:FFFFFF>(MOUSE WHEEL). UTILIZE O ZOOM PARA JOGAR EM TELAS PEQUENAS OU PARA OBTER MAIS PRECISÃO NAS SUAS JOGADAS. TAMBÉM PODE-SE DAR ZOOM USANDO AS <color:FDFDD8>SETAS PARA CIMA E PARA BAIXO NO TECLADO.", "noticias_mapa.png", "CENTER", "vitorias", 0, 50, "humano");	
	
	//SITE:
	%this.criarNoticia("VISITE O SITE WWW.PROJETOIMPERIO.COM", "NO SITE DO PROJETO IMPÉRIO VOCÊ TEM ACESSO A DIVERSAS FUNCIONALIDADES, COMO FÓRUNS DE DISCUSSÃO, RECADOS PESSOAIS, LISTA DE AMIGOS, RANKINGS, VÍDEO-TUTORIAIS, E AINDA FICA SABENDO DAS ÚLTIMAS ATUALIZAÇÕES NO JOGO.", "noticias_site.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("VÍDEO-TUTORIAIS E FÓRUNS DE DICAS", "ASSISTA AOS <color:FDFDD8>VÍDEO-TUTORIAIS NO SITE DO PROJETO IMPÉRIO <color:FFFFFF>PARA APRENDER SOBRE O JOGO E SUAS POSSIBILIDADES. VOCÊ TAMBÉM ENCONTRARÁ DICAS NO <color:FDFDD8>FÓRUM DE DICAS & TRUQUES, <color:FFFFFF>ONDE PODERÁ FAZER PERGUNTAS PARA GMS E OUTROS JOGADORES.", "noticias_site.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("CONVIDE AMIGOS PARA GANHAR CRÉDITOS", "VOCÊ PODE <color:FDFDD8>ENVIAR CONVITES <color:FFFFFF>PARA SEUS AMIGOS PARTICIPAREM DO PROJETO IMPÉRIO. USE O <color:FDFDD8>LINK NO CANTO SUPERIOR ESQUERDO DO SITE <color:FFFFFF>PARA FAZER SEUS CONVITES. ASSIM, <color:FDFDD8>SEMPRE QUE UM CONVIDADO SEU SUBIR DE PATENTE VOCÊ GANHARÁ CRÉDITOS!", "noticias_site.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("DÊ SUGESTÕES PARA MELHORAR O JOGO", "TODA A ESTRUTURA DO JOGO E DO SITE ESTÁ EM CONSTRUÇÃO E A <color:FDFDD8>SUA AJUDA É FUNDAMENTAL <color:FFFFFF>PARA TORNAR O PROJETO IMPÉRIO CADA VEZ MAIS DIVERTIDO! COMPARTILHE SUAS IDEIAS NO FÓRUM DE SUGESTÕES, <color:FDFDD8>TODOS OS POSTS SÃO RESPONDIDOS.", "noticias_site.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("RANKING: QUAL É A SUA COLOCAÇÃO?", "CONSULTE O RANKING DE PERSONAS NO SITE <color:FDFDD8>WWW.PROJETOIMPERIO.COM <color:FFFFFF>PARA VERIFICAR SUA COLOCAÇÃO DENTRE TODOS OS JOGADORES DO PROJETO IMPÉRIO.\nO RANKING É ATUALIZADO <color:FDFDD8>IMEDIATAMENTE APÓS CADA PARTIDA.", "noticias_site.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("BLOG: AS ÚLTIMAS ATUALIZAÇÕES", "AS ÚLTIMAS ATUALIZAÇÕES EFETUADAS NO PROJETO IMPÉRIO SÃO SEMPRE <color:FDFDD8>RELATADAS NO BLOG, <color:FFFFFF>QUE PODE SER ACESSADO ATRAVÉS DO SITE. TAMBÉM É POSSÍVEL <color:FDFDD8>COMENTAR CADA ATUALIZAÇÃO, <color:FFFFFF>DANDO SUAS OPINIÕES E CONTRIBUINDO PARA A OTIMIZAÇÃO DO JOGO.", "noticias_site.png", "CENTER", "vitorias", 0, 9999, "humano");	
		
	//OMNIS:
	%this.criarNoticia("OMNIS: EVOLUA COM MUITA RAPIDEZ", "OS OMNIS PERMITEM QUE VOCÊ COMPRE TECNOLOGIAS DA ACADEMIA IMPERIAL INSTANTANEAMENTE, SEM PESQUISAR.\n <color:FDFDD8>ADQUIRA OMNIS NO SITE WWW.PROJETOIMPERIO.COM E APAVORE SEUS ADVERSÁRIOS!", "noticias_omnis.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("OMNIS: PACOTES COM DESCONTO", "EXISTEM <color:FDFDD8>PACOTES DE OMNIS COM ÓTIMOS DESCONTOS <color:FFFFFF>NO SITE DO PROJETO IMPÉRIO. COMPRANDO O PACOTE DE 1000 OMNIS VOCÊ <color:FDFDD8>ECONOMIZA MAIS DE 20 REAIS E AINDA PODE PAGAR EM DUAS VEZES SEM JUROS NO CARTÃO!", "noticias_omnis.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("OMNIS: GRANDES VANTAGENS NA ACADEMIA", "NA ACADEMIA IMPERIAL AS PESQUISAS FICAM MAIS CARAS CONFORME VOCÊ DESENVOLVE CADA TECNOLOGIA. PORÉM, EM OMNIS OS <color:FDFDD8>PREÇOS SÃO CONGELADOS <color:FFFFFF>QUANDO CHEGAM A 39. POR MAIS CARA QUE SEJA, <color:FDFDD8>NENHUMA PESQUISA CUSTARÁ MAIS DE 39 OMNIS!", "noticias_omnis.png", "CENTER", "vitorias", 0, 9999, "humano");	
	
	//GULOKS:
	%this.criarNoticia("GULOKS: HABITANTES DO PLANETA UNGART", "OS GULOKS SÃO UMA <color:FDFDD8>FORMA DE VIDA ALIENÍGENA <color:FFFFFF>ENCONTRADA EM UNGART. A MAIOR PARTE DA SUA POPULAÇÃO PERMANECE <color:FDFDD8>HIBERNANDO <color:FFFFFF>NAS PROFUNDEZAS DAS CAVERNAS E MARES, <color:FDFDD8>MAS NOVOS INDIVÍDUOS DESPERTAM A CADA DIA.", "noticias_guloks.png", "CENTER", "vitorias", 0, 200, "humano");	
	
	//ACADEMIA:
    %this.criarNoticia("PLANETAS: EXPANDA SEUS HORIZONTES", "DESCUBRA NOVOS PLANETAS NA ACADEMIA IMPERIAL E EXPLORE <color:FDFDD8>MUNDOS ÚNICOS COM RECURSOS ABUNDANTES. <color:FFFFFF>VOCÊ PODE ATÉ MESMO ENCONTRAR ALGUMA <color:FDFDD8>FORMA DE VIDA ALIENÍGENA... <color:FFFFFF>QUEM SABE?", "noticias_planetas.png", "CENTER", "vitorias", 0, 200, "humano");		
	
	//ACHIEVEMENTS:
	%this.criarNoticia("QUEBRA DE SAQUE: DEU ZEBRA!", "GANHAR UMA PARTIDA JOGANDO POR ÚLTIMO É UMA <color:FDFDD8>PROEZA DIFÍCÍL DE ATINGIR, <color:FFFFFF>JÁ QUE OS PRIMEIROS A JOGAR NORMALMENTE CONQUISTAM OS GRUPOS MAIS VALIOSOS. QUEBRE O SAQUE DOS ADVERSÁRIOS PARA GANHAR UM <color:FDFDD8>BÔNUS DE 3 CRÉDITOS.", "noticias_academia.png", "CENTER", "vitorias", 0, 200, "humano");		
	%this.criarNoticia("PARTIDAS LENTAS: EVITE SE PUDER", "AS PARTIDAS DE IMPÉRIO <color:FDFDD8>ACABAM AUTOMATICAMENTE AO FINAL DA DÉCIMA RODADA, <color:FFFFFF>MESMO QUE NINGUÉM BATA ATÉ LÁ. QUANDO UM JOGO CHEGA NA DÉCIMA RODADA <color:FDFDD8>TODOS OS PARTICIPANTES GANHAM MENOS CRÉDITOS.", "noticias_academia.png", "CENTER", "vitorias", 0, 25, "humano");	
	
	//MODOS DE JOGO:
	%this.criarNoticia("JOGO SEM PESQUISAS: EQUILÍBRIO TOTAL", "IMPÉRIO TAMBÉM PODE SER JOGADO <color:FDFDD8>SEM PESQUISAS, <color:FFFFFF>EXATAMENTE COMO É NO TABULEIRO. NESTE MODO DE JOGO OS PARTICIPANTES ESTÃO SEMPRE EQUILIBRADOS, POIS <color:FDFDD8>NÃO CONTAM COM AS TECNOLOGIAS DESENVOLVIDAS NA ACADEMIA IMPERIAL.", "noticias_semPesquisas.png", "CENTER", "vitorias", 0, 100, "humano");	
	%this.criarNoticia("JOGO EM SET: ORDEM ROTATIVA", "NOS JOGOS EM SET A <color:FDFDD8>ORDEM DE JOGADA É ROTATIVA, <color:FFFFFF>SENDO DEFINIDA PELA ORDEM DE JOGADA DA PARTIDA ANTERIOR. ASSIM, TODOS PODEM EXPERIMENTAR AS VANTAGENS DE JOGAR PRIMEIRO E AS MAZELAS DE JOGAR POR ÚLTIMO.", "noticias_set.png", "CENTER", "vitorias", 0, 100, "humano");	
	%this.criarNoticia("JOGANDO COM GIGANTES: RAPIDEZ", "QUANDO VOCÊ ENFRENTAR ADVERSÁRIOS MUITO MAIS FORTES, <color:FDFDD8>TENTE BATER O MAIS RÁPIDO POSSÍVEL. <color:FFFFFF>JOGADORES MAIS FORTES FREQUENTEMENTE TENTARÃO LHE CONVENCER A FAZER PARTIDAS DEMORADAS, NAS QUAIS ELES TÊM GRANDES VANTAGENS.", "noticias_handicap.png", "CENTER", "vitorias", 0, 100, "humano");
	%this.criarNoticia("JOGANDO COM GIGANTES: HANDICAP", "QUANDO VOCÊ FOR UMA DAS PERSONAS MAIS FRACAS EM UM JOGO COM HANDICAP, USE O BÔNUS DE IMPERIAIS PARA <color:FDFDD8>CONSTRUIR BASES NO INÍCIO DO JOGO, <color:FFFFFF>ECONOMIZANDO MOVIMENTOS E CONQUISTANDO GRUPOS VALIOSOS RAPIDAMENTE.", "noticias_handicap.png", "CENTER", "vitorias", 0, 100, "humano");	
	%this.criarNoticia("POKER IMPERIAL: APENAS PARA VETERANOS", "PERSONAS COM <color:FDFDD8>25 OU MAIS VITÓRIAS <color:FFFFFF>PODEM TENTAR A SORTE NO POKER IMPERIAL. DEPOIS, É POSSÍVEL <color:FDFDD8>REVENDER AS FICHAS DE POKER POR CRÉDITOS, <color:FFFFFF>QUE PODEM SER USADOS NA ACADEMIA IMPERIAL PARA FAZER NOVAS PESQUISAS.", "noticias_poker.png", "CENTER", "vitorias", 0, 200, "humano");	
	%this.criarNoticia("JOGO EM DUPLAS: MODO COOPERATIVO", "NOS JOGOS EM DUPLAS PODE-SE COMPARTILHAR ÁREAS, GRUPOS E BASES COM SEU COMPANHEIRO DE DUPLA. <color:FDFDD8>A DUPLA QUE SOMAR MAIS PONTOS VENCE A PARTIDA.\n <color:FFFFFF>APENAS JOGOS COM TRÊS DUPLAS COMPETINDO SERÃO REGISTRADOS.", "noticias_emDuplas.png", "CENTER", "vitorias", 0, 200, "humano");	
		
	//REQUISITOS:
	%this.criarNoticia("VISIONÁRIO: CONSTRUA UM IMPÉRIO", "VISIONÁRIO É AQUELE QUE CONSEGUE <color:FDFDD8>CONSTRUIR UM IMPÉRIO <color:FFFFFF>(10 BASES) E MANTÊ-LO ATÉ O FINAL DA PARTIDA. QUANDO VOCÊ CONSTRÓI UM IMPÉRIO, SUA BARRA DE VISIONÁRIO SOBE, CONTRIBUINDO PARA A <color:FDFDD8>ABERTURA DE NOVAS PESQUISAS TECNOLÓGICAS.", "noticias_academia.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("ARREBATADOR: COMPLETE OS DOIS OBJETIVOS", "ARREBATADOR É AQUELE QUE CONSEGUE <color:FDFDD8>COMPLETAR OS DOIS OBJETIVOS <color:FFFFFF>EM UMA PARTIDA. QUANDO VOCÊ COMPLETA AMBOS OS OBJETIVOS, SUA BARRA DE ARREBATADOR SOBE, CONTRIBUINDO PARA A <color:FDFDD8>ABERTURA DE NOVAS PESQUISAS TECNOLÓGICAS.", "noticias_academia.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("COMERCIANTE: VOCÊ É CONFIÁVEL?", "BONS COMERCIANTES SÃO CONSIDERADOS SEGUROS PORQUE <color:FDFDD8>NÃO DECRETAM MORATÓRIAS. <color:FFFFFF>FINALIZAR UMA PARTIDA TENDO EFETUADO PELO MENOS UM ACORDO E SEM DECRETAR MORATÓRIAS <color:FDFDD8>LHE DARÁ 2 CRÉDITOS, <color:FFFFFF>MESMO QUE VOCÊ NÃO VENÇA O JOGO.", "noticias_recursos.png", "CENTER", "vitorias", 0, 25, "humano");	
	%this.criarNoticia("DIPLOMACIA: A CHAVE PARA A PROSPERIDADE", "GANHAR UMA PARTIDA SEM ATACAR ADVERSÁRIOS VALE O DOBRO DE CRÉDITOS.\nCONSIGA VITÓRIAS DIPLOMÁTICAS PARA <color:FDFDD8>RECEBER MUITOS CRÉDITOS, <color:FFFFFF>QUE PODEM SER USADOS NA ACADEMIA IMPERIAL PARA DESENVOLVER <COLOR:FDFDD8>NOVAS TECNOLOGIAS.", "noticias_diplomacia.png", "CENTER", "vitorias", 0, 25, "humano");	
	
	//A ARTE DA GUERRA:
	%this.criarNoticia("A ARTE DA GUERRA: ATAQUE", "UM COMANDANTE MILITAR DEVE ATACAR ONDE O INIMIGO ESTÁ DESPREVENIDO E DEVE UTILIZAR CAMINHOS QUE PARA O INIMIGO SÃO INESPERADOS.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: VENCER SEM LUTAR", "O PRÊMIO MAIOR DE UMA VITÓRIA É TRIUNFAR POR MEIO DE ESTRATAGEMAS,\nSEM USAR AS TROPAS.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: TÁTICAS", "DURANTE UMA GUERRA, O GENERAL DEVE ADOTAR TÁTICAS FRONTAIS SE QUISER CONFRONTAR O INIMIGO, E TÁTICAS DE SURPRESA SE QUISER CONQUISTAR A VITÓRIA.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: PRIORIDADES", "AQUELE QUE TOMA PRECAUÇÕES EM MUITOS LUGARES ESTARÁ POUCO NUMEROSO EM MUITOS LUGARES.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: TENHA UM PLANO", "NUNCA SE DEVE ATACAR POR CÓLERA E COM PRESSA. É ACONSELHÁVEL TOMAR-SE TEMPO NO PLANEJAMENTO E COORDENAÇÃO DE UMA ESTRATÉGIA.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: CONHECIMENTO", "SE CONHECES OS ADVERSÁRIOS E CONHECES A TI MESMO, NEM EM CEM BATALHAS CORRERÁS PERIGO.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: ESPIONAGEM", "SE NÃO CONHECES OS ADVERSÁRIOS, PORÉM CONHECES A TI MESMO, PERDERÁS UMA BATALHA E GANHARÁS OUTRA.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: IGNORÂNCIA", "SE NÃO CONHECES OS ADVERSÁRIOS NEM CONHECES A TI MESMO, CORRERÁS PERIGO EM CADA BATALHA.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: PERDAS E DANOS", "SE SÓ ÉS CAPAZ DE ASSEGURAR A VITÓRIA DEPOIS DE ENFRENTAR UM ADVERSÁRIO EM UM CONFLITO ARMADO, ESSA VITÓRIA É UMA DURA VITÓRIA.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: INFALÍVEL", "PARA TOMAR INFALIVELMENTE O QUE ATACAS, ATACA ONDE NÃO HÁ DEFESA. PARA MANTER UMA DEFESA INFALIVELMENTE SEGURA, DEFENDE ONDE NÃO HÁ ATAQUE.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
	%this.criarNoticia("A ARTE DA GUERRA: RAPIDEZ", "AS SITUAÇÕES MILITARES SE BASEIAM NA VELOCIDADE: CHEGUE COMO O VENTO, MOVA-SE COMO O RELÂMPAGO, E OS ADVERSÁRIOS NÃO PODERÃO VENCER-TE.\n <color:FDFDD8>- SUN TZU -", "noticias_sunTzu.png", "CENTER", "vitorias", 0, 9999, "humano");	
}


function noticias_handler::setNoticia(%this, %num)
{
	%noticia = %this.getNoticiaPorNumero(%num);
	noticias_tab_titulo_txt.text = %noticia.titulo;
	noticias_tab_txtML.setText("<just:" @ %noticia.just @ ">" @ %noticia.texto @ "\n\n");
	noticias_tab_img.bitmap = "game/data/images/noticias/" @ %noticia.img;
}

function noticias_handler::getNoticiaPorNumero(%this, %num)
{
	for(%i = 0; %i < %this.simNoticias.getCount(); %i++)
	{
		%noticia = %this.simNoticias.getObject(%i);
		if(%noticia.num == %num)
			return %noticia;
	}
}

function noticias_handler::sortearNovaNoticia(%this)
{
	%result = getRandom(%this.simNoticias.getCount());
	%this.setNoticia(%result);
}




